<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\CandidateController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\Map\MapStatsController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\TenantController;
use App\Http\Controllers\TypeAddressController;
use App\Http\Controllers\TypeContactController;
use App\Http\Controllers\TypeDocumentController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\PersonContactController;
use App\Http\Controllers\PersonAddressController;
use App\Http\Controllers\PersonDocumentController;
use App\Http\Controllers\PersonNoteController;
use App\Http\Controllers\PersonFileController;
use App\Http\Controllers\PeopleAvatarController;
use App\Http\Controllers\PeopleUserController;
use App\Http\Controllers\PersonPermissionController;
use App\Http\Controllers\TypePeopleController;
use Illuminate\Support\Facades\Route;

Route::get('/ping', fn () => ['status' => 'ok']);
Route::get('/states/{uf}/geometry', [StateController::class, 'geometry']);
Route::get('/tenants', [TenantController::class, 'index']);

Route::middleware('tenant')->get('/auth/tenant', [AuthController::class, 'tenant']);
Route::middleware('tenant')->post('/auth/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/candidates/search', [CandidateController::class, 'search']);
    Route::get('/people', [PeopleController::class, 'index']);
    Route::post('/people', [PeopleController::class, 'store']);
    Route::put('/people/{id}', [PeopleController::class, 'update']);
    Route::delete('/people/{id}', [PeopleController::class, 'destroy']);
    Route::post('/people/{id}/avatar', [PeopleAvatarController::class, 'store']);
    Route::delete('/people/{id}/avatar', [PeopleAvatarController::class, 'destroy']);
    Route::get('/people/{personId}/permissions', [PersonPermissionController::class, 'index']);
    Route::put('/people/{personId}/permissions/{actionId}', [PersonPermissionController::class, 'update']);
    Route::get('/people/{personId}/user', [PeopleUserController::class, 'show']);
    Route::post('/people/{personId}/user', [PeopleUserController::class, 'store']);
    Route::put('/people/{personId}/user', [PeopleUserController::class, 'update']);
    Route::get('/people/{personId}/contacts', [PersonContactController::class, 'index']);
    Route::post('/people/{personId}/contacts', [PersonContactController::class, 'store']);
    Route::put('/people/{personId}/contacts/{id}', [PersonContactController::class, 'update']);
    Route::delete('/people/{personId}/contacts/{id}', [PersonContactController::class, 'destroy']);
    Route::get('/people/{personId}/addresses', [PersonAddressController::class, 'index']);
    Route::post('/people/{personId}/addresses', [PersonAddressController::class, 'store']);
    Route::put('/people/{personId}/addresses/{id}', [PersonAddressController::class, 'update']);
    Route::delete('/people/{personId}/addresses/{id}', [PersonAddressController::class, 'destroy']);
    Route::get('/people/{personId}/documents', [PersonDocumentController::class, 'index']);
    Route::post('/people/{personId}/documents', [PersonDocumentController::class, 'store']);
    Route::put('/people/{personId}/documents/{id}', [PersonDocumentController::class, 'update']);
    Route::delete('/people/{personId}/documents/{id}', [PersonDocumentController::class, 'destroy']);
    Route::get('/people/{personId}/notes', [PersonNoteController::class, 'index']);
    Route::post('/people/{personId}/notes', [PersonNoteController::class, 'store']);
    Route::put('/people/{personId}/notes/{id}', [PersonNoteController::class, 'update']);
    Route::delete('/people/{personId}/notes/{id}', [PersonNoteController::class, 'destroy']);
    Route::get('/people/{personId}/files', [PersonFileController::class, 'index']);
    Route::post('/people/{personId}/files', [PersonFileController::class, 'store']);
    Route::get('/people/{personId}/files/{id}/download', [PersonFileController::class, 'download']);
    Route::delete('/people/{personId}/files/{id}', [PersonFileController::class, 'destroy']);
    Route::get('/type-people', [TypePeopleController::class, 'index']);
    Route::post('/type-people', [TypePeopleController::class, 'store']);
    Route::put('/type-people/{id}', [TypePeopleController::class, 'update']);
    Route::delete('/type-people/{id}', [TypePeopleController::class, 'destroy']);
    Route::get('/type-contacts', [TypeContactController::class, 'index']);
    Route::post('/type-contacts', [TypeContactController::class, 'store']);
    Route::put('/type-contacts/{id}', [TypeContactController::class, 'update']);
    Route::delete('/type-contacts/{id}', [TypeContactController::class, 'destroy']);
    Route::get('/type-addresses', [TypeAddressController::class, 'index']);
    Route::post('/type-addresses', [TypeAddressController::class, 'store']);
    Route::put('/type-addresses/{id}', [TypeAddressController::class, 'update']);
    Route::delete('/type-addresses/{id}', [TypeAddressController::class, 'destroy']);
    Route::get('/type-documents', [TypeDocumentController::class, 'index']);
    Route::post('/type-documents', [TypeDocumentController::class, 'store']);
    Route::put('/type-documents/{id}', [TypeDocumentController::class, 'update']);
    Route::delete('/type-documents/{id}', [TypeDocumentController::class, 'destroy']);
    Route::post('/tenants', [TenantController::class, 'store']);
    Route::put('/tenants/{id}', [TenantController::class, 'update']);
    Route::get('/tenants/{id}/person', [TenantController::class, 'person']);
    Route::post('/tenants/{id}/person', [TenantController::class, 'storePerson']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::get('/candidates', [CandidateController::class, 'index']);
    Route::get('/map/stats', MapStatsController::class);
    Route::get('/candidacies/{id}/stats', [CandidateController::class, 'stats']);
    Route::get('/candidacies/{id}/cities', [CandidateController::class, 'cities']);
    Route::get('/cities/search', [CityController::class, 'search']);
});
